version: "3.7"
services:
    grafana:
        container_name: pektin-grafana
        restart: always
        image: grafana/grafana-oss:8.5.3
        networks:
            - rp
        environment:
            GF_SERVER_HTTP_PORT: 80
        volumes:
            - ../config/grafana/grafana.ini:/etc/grafana/grafana.ini
            - ../config/grafana/datasources:/etc/grafana/provisioning/datasources/
            - grafana:/var/lib/grafana

networks:
    rp:
        name: rp
volumes:
    grafana:
