version: "3.7"
services:
    grafana:
        container_name: pektin-grafana
        restart: always
        image: grafana/grafana-oss:8.5.3
        networks:
            - prometheus
networks:
    prometheus:
