version: "3.7"
services:
    recursor:
        image: pektin/bind-alpine-docker
        container_name: pektin-recursor
        restart: always
        volumes:
            - ../config/bind/named.conf:/etc/bind/named.conf:ro
        networks:
            - rp

networks:
    rp:
        name: rp
