version: "3.7"
services:
    redis:
        image: redis
        container_name: pektin-redis-arbeiter
        restart: always
        volumes:
            - db:/data
            - ../../config/redis/arbeiter/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - ../../secrets/redis/users.acl:/usr/local/etc/redis/users.acl:ro
        networks:
            - db
            - pektin-gewerkschaft
        command: "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            - R_PEKTIN_GEWERKSCHAFT_PASSWORD=${R_PEKTIN_GEWERKSCHAFT_PASSWORD}
    server:
        image: pektin/server
        container_name: pektin-server
        restart: always
        environment:
            - R_PEKTIN_SERVER_PASSWORD=${R_PEKTIN_SERVER_PASSWORD}
        networks:
            - db
            - rp
        ports:
            - 53:53/udp
            - 53:53/tcp
        depends_on:
            - redis
networks:
    db:
    rp:
        name: rp
    pektin-gewerkschaft:
        name: pektin-gewerkschaft
        external: true

volumes:
    db:
