version: "3.7"
services:
    redis:
        image: redis:6.2.6-alpine
        user: root
        container_name: pektin-redis-arbeiter
        restart: always
        volumes:
            - db:/data
            - ../../secrets/redis/redis.conf:/redis.conf:ro
            - ../../secrets/redis/users.acl:/users.acl:ro
        networks:
            - db
            - pektin-gewerkschaft
        command: "redis-server /redis.conf"
    server:
        image: pektin/server
        container_name: pektin-server
        restart: always
        environment:
            - REDIS_HOSTNAME=pektin-redis-arbeiter
            - REDIS_PASSWORD=${R_PEKTIN_SERVER_PASSWORD}
        networks:
            - db
            - rp
        ports:
            - 53:53/udp
            - 53:53/tcp
        depends_on:
            - redis

networks:
    db:
    rp:
        name: rp
    pektin-gewerkschaft:
        name: pektin-gewerkschaft
        external: true
        driver: overlay

volumes:
    db:
