version: "3.7"
services:
    db:
        image: eqalpha/keydb:alpine_x86_64_v6.2.2
        user: root
        container_name: pektin-db-arbeiter
        restart: always
        volumes:
            - db:/data
            - ../../secrets/db/db.conf:/db.conf:ro
            - ../../secrets/db/users.acl:/users.acl:ro
        networks:
            - db
            - pektin-gewerkschaft
        command: ["keydb-server", "/db.conf"]
    server:
        image: pektin/server
        container_name: pektin-server
        restart: always
        environment:
            - DB_HOSTNAME=pektin-db-arbeiter
            - DB_PASSWORD=${DB_PEKTIN_SERVER_PASSWORD}
        networks:
            - db
            - rp
        ports:
            - 53:53/udp
            - 53:53/tcp
        depends_on:
            - db

networks:
    db:
    rp:
        name: rp
    pektin-gewerkschaft:
        name: pektin-gewerkschaft
        external: true
        driver: overlay
        attachable: true
        driver_opts:
            encrypted:

volumes:
    db:
