version: "3.7"
services:
    db:
        image: pektin/db
        container_name: pektin-db-arbeiter
        restart: always
        cap_add:
            - NET_ADMIN
        volumes:
            - db:/data
            - ../../secrets/db/db.conf:/db.conf:ro
            - ../../secrets/db/users.acl:/users.acl:ro
            - ../../secrets/db/wg0.conf:/etc/wireguard/wg0.conf
        networks:
            - db
        command: ["keydb-server", "/db.conf"]
    server:
        image: pektin/server
        container_name: pektin-server
        restart: always
        environment:
            - DB_HOSTNAME=pektin-db-arbeiter
            - DB_PASSWORD=${DB_PEKTIN_SERVER_PASSWORD}
        networks:
            - db
            - rp
        ports:
            - 53:53/udp
            - 53:53/tcp
        depends_on:
            - db

networks:
    db:
        name: pektin-db
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: fd00:a:a::/48
    rp:
        name: rp
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: fd00:a:b::/48

volumes:
    db:
