version: "3.7"
services:
    redis:
        container_name: pektin-redis-direktor
        volumes:
            - ../config/redis/direktor/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf:ro
        networks:
            - pektin-gewerkschaft
        environment:
            - REDIS_REPLICATION_MODE=master
    api:
        environment:
            - REDIS_URI=redis://pektin-redis-direktor:6379
    server:
        environment:
            - REDIS_URI=redis://pektin-redis-direktor:6379

networks:
    pektin-gewerkschaft:
        name: pektin-gewerkschaft
        driver: overlay
