version: "3.7"
services:
    redis:
        container_name: pektin-redis-direktor
        volumes:
            - ../config/redis/direktor/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf:ro
        networks:
            - pektin-gewerkschaft
        environment:
            - REDIS_REPLICATION_MODE=master
    api:
        environment:
            - REDIS_HOSTNAME=pektin-redis-direktor
            - REDIS_PASSWORD:${R_PEKTIN_API_PASSWORD}
    server:
        environment:
            - REDIS_HOSTNAME=pektin-redis-direktor
            - REDIS_PASSWORD:${R_PEKTIN_SERVER_PASSWORD}

networks:
    pektin-gewerkschaft:
        name: pektin-gewerkschaft
        driver: overlay
