version: "3.7"
services:
    redis:
        container_name: pektin-redis-direktor
        volumes:
            - ../config/redis/direktor/redis.conf:/redis.conf:ro
        networks:
            - pektin-gewerkschaft
    api:
        environment:
            - REDIS_HOSTNAME=pektin-redis-direktor
    server:
        environment:
            - REDIS_HOSTNAME=pektin-redis-direktor

networks:
    pektin-gewerkschaft:
        name: pektin-gewerkschaft
        driver: overlay
        attachable: true
