version: "3.7"
services:
    db:
        container_name: pektin-db-direktor
        volumes:
            - ../config/db/direktor/db.conf:/db.conf:ro
    api:
        environment:
            - DB_HOSTNAME=pektin-db-direktor
    server:
        environment:
            - DB_HOSTNAME=pektin-db-direktor
