version: "3.7"
services:
    ofelia:
        image: mcuadros/ofelia:latest
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            ofelia.enabled: "true"
            ofelia.job-run.rotate.schedule: "@every 80d"
            ofelia.job-run.rotate.image: "pektin/rotate"
