version: "3.7"
services:
    vault:
        image: pektin/vault
        container_name: pektin-vault
        restart: always
        cap_add:
            - IPC_LOCK
        volumes:
            - vault:/vault/file/
            - ../config/vault/:/vault/config/
        command: ["server"]
        environment:
            - VAULT_API_ADDR=${VAULT_API_ADDR}
        networks:
            - vault
            - rp
    api:
        image: pektin/api
        container_name: pektin-api
        restart: always
        environment:
            - V_PEKTIN_API_PASSWORD=${V_PEKTIN_API_PASSWORD}
            - V_PEKTIN_API_USER_NAME=${V_PEKTIN_API_USER_NAME}
            - DB_PASSWORD=${DB_PEKTIN_API_PASSWORD}
            - USE_POLICIES=${USE_POLICIES}
            - RUST_LOG=${API_LOGGING}
        networks:
            - vault
            - db
            - rp
            - api
        depends_on:
            - db
            - vault
    db:
        image: pektin/db
        container_name: pektin-db
        restart: always
        cap_add:
            - NET_ADMIN
        volumes:
            - db:/data
            - ../config/db/db.conf:/db.conf:ro
            - ../secrets/db/users.acl:/users.acl:ro
            - ../secrets/db/wg0.conf:/etc/wireguard/wg0.conf
        networks:
            - db
        command: ["keydb-server", "/db.conf"]
        ports:
            - 51820:51820/udp
    server:
        image: pektin/server
        container_name: pektin-server
        restart: always
        environment:
            - DB_PASSWORD=${DB_PEKTIN_SERVER_PASSWORD}
            - RUST_LOG=${SERVER_LOGGING}
        networks:
            - db
            - rp
        ports:
            - 53:53/udp
            - 53:53/tcp
        depends_on:
            - db

networks:
    vault:
    db:
    rp:
        name: rp
    api:

volumes:
    vault:
    db:
