version: "3.7"
services:
    vault:
        image: vault
        container_name: pektin-vault
        restart: always
        cap_add:
            - IPC_LOCK
        volumes:
            - vault:/vault/file/
            - ../config/vault/:/vault/config/
            - ../logs/vault/:/vault/logs
        command: server
        #
        #environment:
        #  - VAULT_API_ADDR=
        networks:
            - vault
            - rp
    api:
        image: pektin/api
        container_name: pektin-api
        restart: always
        environment:
            - V_PEKTIN_API_PASSWORD=${V_PEKTIN_API_PASSWORD}
            - REDIS_PASSWORD=${R_PEKTIN_API_PASSWORD}
        networks:
            - vault
            - db
            - rp
        depends_on:
            - redis
            - vault
    redis:
        image: redis:6.2.6-alpine
        user: root
        container_name: pektin-redis
        restart: always
        volumes:
            - db:/data
            - ../config/redis/redis.conf:/redis.conf:ro
            - ../secrets/redis/users.acl:/users.acl:ro
        networks:
            - db
        command: "redis-server /redis.conf"
    server:
        image: pektin/server
        container_name: pektin-server
        restart: always
        environment:
            - REDIS_PASSWORD=${R_PEKTIN_SERVER_PASSWORD}
        networks:
            - db
            - rp
        ports:
            - 53:53/udp
            - 53:53/tcp
        depends_on:
            - redis

networks:
    vault:
    db:
    rp:
        name: rp

volumes:
    vault:
    db:
