version: "3.7"
services:
    vault:
        image: vault
        container_name: pektin-vault
        restart: always
        cap_add:
            - IPC_LOCK
        volumes:
            - vault:/vault/file/
            - ../config/vault/:/vault/config/
            - ../logs/vault/:/vault/logs
        command: server
        # TODO: GENERATE FULL VAUL API URL WITH INSTALL INTO .env
        #environment:
        #  - VAULT_API_ADDR=
        networks:
            - vault
            - rp
    ui:
        image: pektin/ui
        container_name: pektin-ui
        restart: always
        environment:
            - CSP_CONNECT_SRC=${CSP_CONNECT_SRC}
        networks:
            - rp
    api:
        image: pektin/api
        container_name: pektin-api
        restart: always
        environment:
            - V_PEKTIN_API_ROLE_ID=${V_PEKTIN_API_ROLE_ID}
            - V_PEKTIN_API_SECRET_ID=${V_PEKTIN_API_SECRET_ID}
            - R_PEKTIN_API_PASSWORD=${R_PEKTIN_API_PASSWORD}
        networks:
            - vault
            - db
            - rp
        depends_on:
            - redis
            - vault

    redis:
        image: redis
        container_name: pektin-redis
        restart: always
        volumes:
            - db:/data
            - ../config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - ../secrets/redis/users.acl:/usr/local/etc/redis/users.acl:ro
        networks:
            - db
        command: "redis-server /usr/local/etc/redis/redis.conf"
    server:
        image: pektin/server
        container_name: pektin-server
        restart: always
        environment:
            - R_PEKTIN_SERVER_PASSWORD=${R_PEKTIN_SERVER_PASSWORD}
        networks:
            - db
        ports:
            - 53:53/udp
            - 53:53/tcp
        depends_on:
            - redis

networks:
    vault:
    db:
    rp:
        name: rp
volumes:
    vault:
    db:
