version: "3.7"
services:
    rp:
        container_name: rp
        image: traefik:2.6
        restart: always
        ports:
            - 80:80/tcp
            - 443:443/udp
            - 443:443/tcp
            - 853:853/tcp
        networks:
            - rp
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ../secrets/letsencrypt:/letsencrypt
            - ../config/traefik/traefik.yml:/traefik/traefik.yaml
        command:
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --experimental.http3=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http3={}
            - --certificatesresolvers.default.acme.dnschallenge=true
            - --certificatesresolvers.default.acme.dnschallenge.provider=pdns
            - --certificatesresolvers.default.acme.email=${LETSENCRYPT_EMAIL}
            - --certificatesresolvers.default.acme.storage=/letsencrypt/acme.json
            - --providers.file.filename=/traefik/traefik.yaml

            - --entrypoints.dot.address=:853

        labels:
            traefik.enable: "true"
            # redirect http to https
            traefik.http.routers.http-catchall.rule: "hostregexp(`{host:.+}`)"
            traefik.http.routers.http-catchall.entrypoints: "web"
            traefik.http.routers.http-catchall.middlewares: "redirect-to-https@docker"
            traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"
            traefik.http.middlewares.redirect-to-https.redirectscheme.permanent: "true"

networks:
    rp:
        name: rp
