version: "3.7"
services:
    vault:
        labels:
            traefik.enable: "true"
            traefik.docker.network: rp
            traefik.http.routers.pektin-vault.tls.certresolver: "default"
            traefik.http.routers.pektin-vault.tls.domains[0].main: "${VAULT_DOMAIN}"
            traefik.http.routers.pektin-vault.tls.domains[0].sans: "*.${VAULT_DOMAIN}"
            traefik.http.routers.pektin-vault.rule: "Host(`${VAULT_CONCAT_DOMAIN}`)"
            traefik.http.routers.pektin-vault.tls: "true"
            traefik.http.routers.pektin-vault.entrypoints: "websecure"
            traefik.http.services.pektin-vault.loadbalancer.server.port: "8200"
    ui:
        labels:
            traefik.enable: "true"
            traefik.docker.network: rp
            traefik.http.routers.pektin-ui.tls.certresolver: "default"
            traefik.http.routers.pektin-ui.tls.domains[0].main: "${UI_DOMAIN}"
            traefik.http.routers.pektin-ui.tls.domains[0].sans: "*.${UI_DOMAIN}"
            traefik.http.routers.pektin-ui.rule: "Host(`${UI_CONCAT_DOMAIN}`)"
            traefik.http.routers.pektin-ui.tls: "true"
            traefik.http.routers.pektin-ui.entrypoints: "websecure"
            traefik.http.services.pektin-ui.loadbalancer.server.port: "80"
    api:
        labels:
            traefik.enable: "true"
            traefik.docker.network: rp
            traefik.http.routers.pektin-api.tls.certresolver: "default"
            traefik.http.routers.pektin-api.tls.domains[0].main: "${API_DOMAIN}"
            traefik.http.routers.pektin-api.tls.domains[0].sans: "*.${API_DOMAIN}"
            traefik.http.routers.pektin-api.rule: "Host(`${API_CONCAT_DOMAIN}`)"
            traefik.http.routers.pektin-api.tls: "true"
            traefik.http.routers.pektin-api.entrypoints: "websecure"
            traefik.http.services.pektin-api.loadbalancer.server.port: "80"
    server:
        labels:
            traefik.enable: "true"
            traefik.docker.network: rp
            traefik.tcp.routers.pektin-server-dot.tls.certresolver: "default"
            traefik.tcp.routers.pektin-server-dot.tls.domains[0].main: "${SERVER_DOMAIN}"
            traefik.tcp.routers.pektin-server-dot.tls.domains[0].sans: "*.${SERVER_DOMAIN}"
            traefik.tcp.routers.pektin-server-dot.rule: "HostSNI(`*`)"
            traefik.tcp.routers.pektin-server-dot.tls: "true"
            traefik.tcp.routers.pektin-server-dot.entrypoints: "dot"
            traefik.tcp.services.pektin-server-dot.loadbalancer.server.port: "53"
