version: "3.7"
services:
    vault:
        labels:
            traefik.enable: "true"
            traefik.http.routers.pektin-vault.tls.certresolver: "default"
            traefik.http.routers.pektin-vault.tls.domains[0].main: "${DOMAIN}"
            traefik.http.routers.pektin-vault.tls.domains[0].sans: "*.${DOMAIN}"
            traefik.http.routers.pektin-vault.rule: "Host(`${VAULT_SUBDOMAIN}.${DOMAIN}`)"
            traefik.http.routers.pektin-vault.tls: "true"
            traefik.http.routers.pektin-vault.entrypoints: "websecure"
            traefik.http.services.pektin-vault.loadbalancer.server.port: "8200"
    ui:
        labels:
            traefik.enable: "true"
            traefik.http.routers.pektin-ui.tls.certresolver: "default"
            traefik.http.routers.pektin-ui.tls.domains[0].main: "${DOMAIN}"
            traefik.http.routers.pektin-ui.tls.domains[0].sans: "*.${DOMAIN}"
            traefik.http.routers.pektin-ui.rule: "Host(`${UI_SUBDOMAIN}.${DOMAIN}`)"
            traefik.http.routers.pektin-ui.tls: "true"
            traefik.http.routers.pektin-ui.entrypoints: "websecure"
            traefik.http.services.pektin-ui.loadbalancer.server.port: "80"
    api:
        labels:
            traefik.enable: "true"
            traefik.http.routers.pektin-api.tls.certresolver: "default"
            traefik.http.routers.pektin-api.tls.domains[0].main: "${DOMAIN}"
            traefik.http.routers.pektin-api.tls.domains[0].sans: "*.${DOMAIN}"
            traefik.http.routers.pektin-api.rule: "Host(`${API_SUBDOMAIN}.${DOMAIN}`)"
            traefik.http.routers.pektin-api.tls: "true"
            traefik.http.routers.pektin-api.entrypoints: "websecure"
            traefik.http.services.pektin-api.loadbalancer.server.port: "80"
